import './globals.css';
import FooterLayout from '@/layouts/footer';
import HeaderLayout from '@/layouts/header';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={`${inter.className} container-screen`}>
        <HeaderLayout />
        {children}
        {/* <FooterLayout /> */}
      </body>
    </html>
  );
}
